### ISSUE TITLE
Can you provide a usable example 

### ISSUE THREAD

**Issue by timewalkerF** [bitextor/neural-document-aligner#1]
Can you provide a usable example

**Comment by cgr71ii** [comment]
Hi! The provided example which is in the README is valid, you just need to change the path for the embeddings where they will be stored if they don't exist (I have changed the paths to `/tmp/{src,trg}_embedding`):

```bash
echo -e \
"TmV1cmFsIERvY3VtZW50IEFsaWduZXIKc3JjIGRvYwo=\thttps://www.this_is_a_url.com/resource1\tsrc\n"\
"TmV1cmFsIERvY3VtZW50IEFsaWduZXIKdHJnIGRvYwo=\thttps://www.this_is_a_url.com/resource2\ttrg"  | \
\
neural-document-aligner - /tmp/src_embedding /tmp/trg_embedding \
                        --docalign-strategy 'faiss' --weights-strategy 0 \
                        --merging-strategy 3 --results-strategy 0 \
                        --emb-optimization-strategy 2 --gen-emb-optimization-strategy 2 \
                        --output-with-idxs --paths-to-docs-are-base64-values \
                        --threshold 0.7
```

The output I got from this execution is:
```
1	1	0.897887110710144
```

**Comment by timewalkerF** [comment]
![3dfef3b4976ac2c546bef5e59a55f01](https://user-images.githubusercontent.com/30802962/141078756-6da965e8-14c5-41ea-84e7-2ae4528c43a5.png)

**Comment by timewalkerF** [comment]
![image](https://user-images.githubusercontent.com/30802962/141079120-135e8864-b6c4-4e85-9a18-29cc52c9d656.png)
Automatically Killed .. Why?

**Comment by cgr71ii** [comment]
Could you provide more info? Are you using GPU? If so, what are the specifications?

Try `--logging-level 0` in order to obtain more information, and which value returns `echo $?` just when the process is killed?

**Comment by timewalkerF** [comment]
![1636534350(1)](https://user-images.githubusercontent.com/30802962/141081199-f11b276c-68fc-4f7c-85f4-abacb6575019.png)
I use a virtual machine, gpu 2070 cpu i7 8700k

**Comment by cgr71ii** [comment]
And the value of `echo $?`?

From [StackOverflow](https://stackoverflow.com/questions/726690/what-killed-my-process-and-why): "If the user or sysadmin did not kill the program the kernel may have. The kernel would only kill a process under exceptional circumstances such as extreme resource starvation (think mem+swap exhaustion)". Might this be the problem? Are you running out of memory or disk? The problem does not seem related to `neural-document-aligner` since the process it is being killed, apparently, by other element (e.g. kernel, other processes).

**Comment by lpla** [comment]
Unable to reproduce this issue in any environment tested in this month. Please reopen if necessary.
